server:
  port: 8901

spring:
  profile: heroku
  datasource:
    url: ${DB_URL_AUTH}
    username: ${DB_USERNAME_AUTH}
    password: ${DB_PASSWORD_AUTH}
    driver-class-name: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ssl: true
        sslfactory: org.postgresql.ssl.NonValidatingFactory
        show_sql: true
        max_fetch_depth: 3
        temp:
          use_jdbc_metadata_defaults: false
