application:
  name: app-accounting
  
server:
  port: ${PORT:10150}
  
spring:
  profile: heroku
  datasource:
    url: ${DB_URL_ACCOUNT:jdbc:postgresql://ec2-54-217-208-105.eu-west-1.compute.amazonaws.com:5432/d78kp44e5carll}
    username: ${DB_USERNAME_ACCOUNT}
    password: ${DB_PASSWORD_ACCOUNT}
    driver-class-name: org.postgresql.Driver
    validationQuery: "SELECT 1"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ssl: true
        sslfactory: org.postgresql.ssl.NonValidatingFactory
        show_sql: true
        max_fetch_depth: 3
        temp:
          use_jdbc_metadata_defaults: false
